version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: audite_postgres_prod
    environment:
      POSTGRES_DB: audite
      POSTGRES_USER: audite_user
      POSTGRES_PASSWORD: audite_password_2024
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U audite_user -d audite"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  backend:
    build: 
      context: ./audite
      dockerfile: Dockerfile
    container_name: audite_backend_prod
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://audite_user:audite_password_2024@postgres:5432/audite
      - SECRET_KEY=your-secret-key-change-in-production
      - JWT_SECRET_KEY=your-jwt-secret-change-in-production
      - JWT_ACCESS_TOKEN_EXPIRES=43200
      - JWT_REFRESH_TOKEN_EXPIRES=604800
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=Audite2024SecurePass!
      - ADMIN_EMAIL=admin@audite.com
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./audite-frontend-explorer
      dockerfile: Dockerfile
    container_name: audite_frontend_prod
    ports:
      - "80:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data: